project_id = "ltgampdtawuefwwayncx"

[functions.chat]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.composio]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = false

[functions.code-sandbox]
verify_jwt = false

[functions.sprites-sandbox]
verify_jwt = false

[functions.github-repo]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.vercel-deploy]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.otp]
verify_jwt = false

[functions.oauth-authorize]
verify_jwt = false

[functions.oauth-token]
verify_jwt = false

[functions.oauth-userinfo]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.oauth-deduct-credits]
verify_jwt = false

[functions.oauth-check-credits]
verify_jwt = false
