project_id = "ltgampdtawuefwwayncx"

[functions.chat]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.composio]
verify_jwt = false
